### ISSUE TITLE
java.lang.IllegalArgumentException: "Media is read-only"

### ISSUE THREAD

**Issue by jonasborggren** [lvillani/android-cropimage#36]
[Stackoverflow Question](http://stackoverflow.com/questions/28945863/cropimage-shows-media-is-read-only)

I have a problem where selecting a photo with picker intent and then cropping the picture gets denied and the reason is

```java
java.lang.IllegalArgumentException: Media is read-only
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
    at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:148)
    at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:618)
    at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:939)
    at android.content.ContentResolver.openOutputStream(ContentResolver.java:686)
    at android.content.ContentResolver.openOutputStream(ContentResolver.java:662)
    at com.android.camera.CropImage.saveOutput(CropImage.java:337)
    at com.android.camera.CropImage.access$500(CropImage.java:58)
    at com.android.camera.CropImage$4.run(CropImage.java:327)
    at com.android.camera.Util$BackgroundJob.run(Util.java:388)
    at java.lang.Thread.run(Thread.java:818)
```

Not sure if this is caused by this library.

**Comment by lvillani** [comment]
Your app manifest should include

```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
and/or:

```xml
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

**Comment by jonasborggren** [comment]
Hey, I missed adding these to the question. I have these in my manifest.

**Comment by lvillani** [comment]
I'm not sure why you're getting that error. Could you provide the information `greenapps` [asked you](http://stackoverflow.com/questions/28945863/cropimage-shows-media-is-read-only#comment46151020_28945863) on SO?

**Comment by lvillani** [comment]
Closing due to inactivity. Feel free to reopen if necessary.

**Comment by jonasborggren** [comment]
I'm back here again..

        java.lang.IllegalArgumentException: Media is read-only
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
            at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:148)
            at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:620)
            at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:939)
            at android.content.ContentResolver.openOutputStream(ContentResolver.java:686)
            at android.content.ContentResolver.openOutputStream(ContentResolver.java:662)
            at com.android.camera.CropImage.saveOutput(CropImage.java:342)
            at com.android.camera.CropImage.access$500(CropImage.java:58)
            at com.android.camera.CropImage$4.run(CropImage.java:332)
            at com.android.camera.Util$BackgroundJob.run(Util.java:388)
            at java.lang.Thread.run(Thread.java:818)

I have all these in my manifest

    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

    <uses-feature android:name="android.hardware.camera.autofocus"/>
    <uses-permission android:name="android.permission.MANAGE_DOCUMENTS"/>

How i open the gallery

    public void openGallery( View v ) {
        Intent intent;
        if ( Build.VERSION.SDK_INT < 19 ) {
            intent = new Intent();
            intent.setAction( Intent.ACTION_GET_CONTENT );
            intent.putExtra( "android.intent.extra.LOCAL_ONLY", true );
            intent.setType( "image/*" );
            startActivityForResult( intent, MainActivity.REQUEST_IMAGE_FROM_GALLERY );
        } else {
            intent = new Intent( Intent.ACTION_OPEN_DOCUMENT );
            intent.addCategory( Intent.CATEGORY_OPENABLE );
            intent.putExtra( "android.intent.extra.LOCAL_ONLY", true );
            intent.setType( "image/*" );
            startActivityForResult( intent, MainActivity.REQUEST_IMAGE_FROM_GALLERY );
        }
    }

In onactivityresult

    MyCropIntent cropImage;
    Uri croppedUri = data.getData();
    Bitmap b = getBitmapFromUri( croppedUri );

    ByteArrayOutputStream bos = new ByteArrayOutputStream();
    b.compress( Bitmap.CompressFormat.PNG, 0, bos );
    byte[] bitmapdata = bos.toByteArray();
    FileOutputStream fos = new FileOutputStream( tempFile );
    fos.write( bitmapdata );
    fos.close();

    MyCropIntent cropImage = new MyCropIntent( 10, 10, 1024, 1024, Uri.fromFile( tempFile ) );
    croppedUri = Uri.fromFile( tempFile );
    cropImage.setSourceImage( croppedUri );
    cropImage.setOutputQuality( 99 );
    cropImage.setOutlineColor( getResources().getColor( R.color.accent ) );
    startActivityForResult( cropImage.getIntent( this ), REQUEST_CROP_IMAGE );

tempFile (called before opening camera activity that has a gallery button)

    private File createImageFile() throws IOException {
        String timeStamp = new SimpleDateFormat( "yyyyMMdd_HHmmss" ).format( new Date() );
        String imageFileName = "JPEG_" + timeStamp + "_";
        File storageDir = Environment.getExternalStoragePublicDirectory( Environment.DIRECTORY_PICTURES );
        tempFile = File.createTempFile( imageFileName, ".jpg", storageDir );
        tempFile.createNewFile();
        return tempFile;
    }
