### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by dogo** [lvillani/android-cropimage#44]
Asus T00J Zenfone 5
Android 4.4.2
```
06-17 09:55:09.445  29477-29477/com.demo.test E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.demo.test, PID: 29477
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3, result=-1, data=null} to activity {com.demo.test/com.demo.test.activities.DemoActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.demo.test/com.android.camera.CropImage}; have you declared this activity in your AndroidManifest.xml?
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3532)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3575)
            at android.app.ActivityThread.access$1300(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:149)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.demo.test/com.android.camera.CropImage}; have you declared this activity in your AndroidManifest.xml?
            at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1628)
            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
            at android.app.Activity.startActivityForResult(Activity.java:3532)
            at android.app.Activity.startActivityForResult(Activity.java:3458)
            at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
            at com.demo.test.activities.DemoActivity.onActivityResult(DemoActivity.java:133)
            at android.app.Activity.dispatchActivityResult(Activity.java:5603)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3528)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3575)
            at android.app.ActivityThread.access$1300(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:149)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by dogo** [comment]
Never mind, was missing <activity android:name="com.android.camera.CropImage"/> at the manifest file.
